import os from "node:os"
import path from "node:path"
import readline from "node:readline"
import ora from "ora"
import { callServer, callServerStream, type ServerError } from "../lib/server.js"
import { ensureSysbase, getSelectedModel, getSysbasePath, getReasoningEnabled, getAuthToken, getPlanMode, getTaskDisplaySelective } from "../lib/sysbase.js"
import { executeTool, executeToolsBatch } from "./executor.js"
import { isSafeReadOnlyCommand } from "./safe-commands.js"
import { formatBatchHeading } from "./tool-meta.js"
import { chunkPlanEventFromResponse } from "./chunk-plan-event.js"
import { readFileTool, computeLineDiff } from "./tools.js"
import { clearRunDiffs } from "./diff.js"
import { getOrBuildIndex, compactTree } from "./indexer.js"
import { ensureActiveChat } from "../commands/chats.js"
import {
  colors,
  BOX,
  boxTop,
  boxMid,
  boxBot,
  revealReasoning,
  formatToolLabel,
  isHiddenStep,
  renderMarkdown,
  renderPipelineBox,
  renderChunkProgress,
  printStepTransition,
} from "../cli/render.js"
import {
  enableDiffExpand,
  disableDiffExpand,
  startDiffKeyListener,
} from "../cli/diff-preview.js"
import { renderToolResultPreview } from "../cli/tool-result-preview.js"
import { renderReasoningBrief, renderDecisionBrief } from "../cli/reasoning-display.js"
import { classifyResponse, makeRetryBudget, noteSuccess, type RetryBudget } from "./state-machine.js"
import { recordRunSummary } from "./usage-log.js"
import { getReasoningPeekExpansions, resetReasoningPeekExpansions } from "../ui/components/ReasoningPeek.js"
import { getNullToolRejections, resetNullToolRejections, getImportsStrippedCount, resetImportsStrippedCount, getDotfileFilterCorrections, resetDotfileFilterCorrections, getAlreadyCreatedRejectionCount, resetAlreadyCreatedRejectionCount, clearCreatedPaths, getBatchCapEnforcedCount, resetBatchCapEnforcedCount, getBatchReorderedCount, resetBatchReorderedCount } from "./executor.js"
import { getScrollGlitchPauseFiredCount, resetScrollGlitchPauseFiredCount } from "../ui/animation/use-frame.js"
import { getSpinnerActionLabelFired, resetSpinnerActionLabelFired } from "../ui/spinner-label-format.js"
import { getStreamPreviewEverShown, resetStreamPreviewEverShown } from "./tools.js"
import { getPermissionModalShownCount, resetPermissionModalShownCount } from "../cli/permission-prompt.js"
import { getWindowsShellErrorsCaught, resetWindowsShellErrorsCaught } from "./tools.js"
import { getNonRetryable5xxCount, resetNonRetryable5xxCount } from "../lib/server.js"
import { estimateTokens as cliEstimateTokens } from "./token-estimate.js"
import { startJobStatusBar, stopJobStatusBar } from "../cli/job-status.js"
import { list as listBackgroundJobs, cleanupRun as cleanupBackgroundJobs } from "./background-jobs.js"
import { createChunkSnapshot, cleanupChunkSnapshots, rollbackToChunk } from "./git.js"
import { askOffCourse, type OffCourseEvidence } from "../cli/off-course-prompt.js"
import { registerSpinner, unregisterSpinner } from "../cli/spinner-control.js"
import { emitAgent, isInkActive, shouldRenderInlineForLegacy } from "./events.js"

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

/**
 * Phase 12 Stage 4: emit tool_start / tool_end events around any tool
 * dispatch so the Ink AgentStream can render a <ToolCard> for each one.
 *
 * No-op in legacy console mode (the existing console.log lines below
 * still carry the same info for that path). When `runFn` throws we
 * still emit the matching tool_end with ok=false so the card transitions
 * to the error state — then re-throw so the existing error handling
 * upstream is unaffected.
 *
 * The `id` is generated by the caller via `nextToolEventId()` so the
 * agent loop can pair start/end deterministically (and we don't tie
 * tool ids to the tool name, which collides on repeated calls).
 */
let toolEventCounter = 0
function nextToolEventId(): string {
  toolEventCounter += 1
  return `t${toolEventCounter}`
}

async function surfaceToolCall<T>(
  id: string,
  tool: string,
  label: string,
  args: Record<string, unknown> | undefined,
  runFn: () => Promise<T>,
): Promise<T> {
  if (!isInkActive()) return runFn()
  emitAgent({ type: "tool_start", id, tool, label, args })
  try {
    const out = await runFn()
    emitAgent({ type: "tool_end", id, ok: true })
    return out
  } catch (err) {
    emitAgent({ type: "tool_end", id, ok: false, error: (err as Error).message })
    throw err
  }
}

/**
 * Phase 12 Stage 4 batch variant: emit one tool_start per tool in the
 * batch BEFORE the batch runs, then end ALL with the same outcome
 * (the batch executor doesn't return per-tool failures via a thrown
 * error — the per-tool outcome lives in the response payload, which
 * is processed separately upstream). If the entire batch throws, all
 * cards transition to error.
 */
async function surfaceToolBatch<T>(
  toolCalls: ReadonlyArray<{ tool: string; args: Record<string, unknown> }>,
  runFn: () => Promise<T>,
): Promise<T> {
  if (!isInkActive()) return runFn()
  const ids = toolCalls.map((tc) => {
    const id = nextToolEventId()
    const label = formatToolLabel(tc.tool, tc.args) ?? tc.tool
    // Phase 14 Stage 2: include args so the new ActionCard can derive
    // its own Verb(target) header on the cli side. Existing label still
    // emitted for back-compat with consumers that already use it.
    emitAgent({ type: "tool_start", id, tool: tc.tool, label, args: tc.args })
    return id
  })
  try {
    const out = await runFn()
    for (const id of ids) emitAgent({ type: "tool_end", id, ok: true })
    return out
  } catch (err) {
    const msg = (err as Error).message
    for (const id of ids) emitAgent({ type: "tool_end", id, ok: false, error: msg })
    throw err
  }
}

/**
 * Phase 11 Stage 5: one-line copy describing a transition between awareness
 * states. Returns null when the transition isn't worth surfacing (e.g.
 * recovery from off_course → on_track is a positive signal but doesn't need
 * its own line — the badge flip in the next chunk-progress render carries it).
 */
function describeAwarenessTransition(
  from: "on_track" | "off_course" | "blocked",
  to: "on_track" | "off_course" | "blocked",
): string | null {
  if (from === to) return null
  if (from === "on_track" && to === "off_course") {
    return colors.warning("⚠ ") + colors.muted("confidence dipped — watching for drift")
  }
  if (to === "blocked") {
    // The off-course modal will appear immediately after this; this line
    // tees it up so the user sees why the prompt is interrupting them.
    return colors.error("✖ ") + colors.muted("blocked — handing off")
  }
  // Recoveries (e.g. blocked → on_track after a redirect) are surfaced via
  // the cooldown skip log; no extra line needed.
  return null
}

/**
 * Phase 16-fixup (Bug 2): filter generic SSE phase labels.
 *
 * The server emits `phase` events with labels like `"calling AI model..."`,
 * `"loading project context..."`, `"processing tool result..."`. These add
 * no information the user can't already see from the spinner being on, and
 * they SUPPRESS the RichSpinner's own verb cycle (`thinking… hmm…
 * debugging… searching…`) which is what makes the spinner feel alive.
 *
 * The fix: when the phase label is one of these generic ones, return ""
 * so the spinner falls back to its built-in cycle. Specific labels that
 * carry actual progress information (tool prep, file paths) pass through.
 */
const GENERIC_PHASE_LABEL_RE = /^(?:calling AI model|loading project context|processing tool result|response ready)\.{0,3}$/i

function suppressGenericPhaseLabel(label: string): string {
  return GENERIC_PHASE_LABEL_RE.test(label.trim()) ? "" : label
}

/**
 * Spinner shim: lets the existing `spinner.text = …` / `spinner.start()` /
 * `spinner.stop()` callsites work whether we're driving an `ora` instance
 * (legacy console mode) or emitting events to the Ink `<AgentStream>`.
 *
 * In Ink mode we deliberately don't render anything to the terminal — the
 * AgentStream component owns the visible region. Without this, ora and Ink
 * would both draw a "thinking..." line at the same position.
 */
type Ora = ReturnType<typeof ora>

function createSpinner(): Ora {
  if (isInkActive()) {
    // Initial text is empty so the Ink <RichSpinner> takes over with its
    // own ~22-verb cycle (`thinking… hmm… debugging… searching…`). The
    // agent overrides this with specific labels (server phase events,
    // tool prep, etc.) via `spinner.text =` calls below; whenever those
    // clear out we fall back to the cycle instead of repeating a single
    // static `thinking…` for the duration of a long pause.
    let current = ""
    emitAgent({ type: "spinner", text: current })
    // Stub mimicking the slice of the ora interface the agent + diff-preview
    // listener actually use. Anything unimplemented (succeed/render/clear/…)
    // returns the stub so chained calls don't blow up.
    const stub = {
      get text() { return current },
      set text(v: string) { current = v; emitAgent({ type: "spinner", text: v }) },
      start(text?: string) { if (text) current = text; emitAgent({ type: "spinner", text: current }); return stub },
      stop() { emitAgent({ type: "spinner_stop" }); return stub },
      fail(text?: string) {
        emitAgent({ type: "spinner_stop" })
        if (text) emitAgent({ type: "log", level: "error", text })
        return stub
      },
      succeed() { emitAgent({ type: "spinner_stop" }); return stub },
      warn() { emitAgent({ type: "spinner_stop" }); return stub },
      info() { emitAgent({ type: "spinner_stop" }); return stub },
      clear() { return stub },
      render() { return stub },
      isSpinning: true,
    }
    return stub as unknown as Ora
  }
  return ora({
    text: colors.muted("thinking..."),
    prefixText: "  ",
    spinner: "dots",
    color: "magenta",
  }).start()
}

// ─── User input prompt ───

function askUser(question: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
  return new Promise((resolve) => {
    rl.question(colors.accent("  > "), (answer) => {
      rl.close()
      resolve(answer.trim())
    })
  })
}

function resolveFileMentions(prompt: string, cwd: string): { prompt: string; mentions: Array<{ path: string; absolute: string }> } {
  const mentions: Array<{ path: string; absolute: string }> = []
  const resolved = prompt.replace(/@([\w./-]+)/g, (_match, filePath: string) => {
    const absolute = path.resolve(cwd, filePath)
    mentions.push({ path: filePath, absolute })
    return filePath
  })
  return { prompt: resolved, mentions }
}

interface RunAgentParams {
  prompt: string
  command?: string | null
  model?: string | null
}

export async function runAgent({ prompt, command = null, model = null }: RunAgentParams): Promise<Record<string, unknown> | undefined> {
  await ensureSysbase()

  const authToken = await getAuthToken()
  if (!authToken) {
    console.log("")
    console.log(colors.warning("  ⚠ You must be logged in to use Sysflow"))
    console.log("")
    console.log(colors.muted("  Run ") + colors.accent("sys login") + colors.muted(" or ") + colors.accent("sys register") + colors.muted(" to get started"))
    console.log("")
    return
  }

  const selectedModel = model || (await getSelectedModel())
  const hasReasoning = await getReasoningEnabled()
  const planMode = await getPlanMode()

  const chatUid = await ensureActiveChat()
  if (!chatUid) {
    console.log("")
    console.log(colors.warning("  ⚠ Could not establish a chat session"))
    console.log(colors.muted("  Check your connection and try again, or run ") + colors.accent("sys chat") + colors.muted(" to select one"))
    console.log("")
    return
  }

  const { prompt: cleanPrompt, mentions } = resolveFileMentions(prompt, process.cwd())

  const mentionedFiles: Array<{ path: string; content: string }> = []
  for (const m of mentions) {
    try {
      const result = await readFileTool(m.absolute)
      mentionedFiles.push({ path: m.path, content: result.content })
    } catch {
      // file doesn't exist, skip
    }
  }

  const fileIndex = await getOrBuildIndex(process.cwd(), getSysbasePath())
  const dirTree = compactTree(fileIndex)

  console.log("")

  const spinner = createSpinner()
  // Legacy modal helpers (permission prompt, retry log) still call
  // pauseSpinner/resumeSpinner via the registered ora ref. In Ink mode the
  // spinner is event-driven so those pause/resume calls become no-ops on
  // the registered instance — the AgentStream drives its own rendering.
  if (!isInkActive()) registerSpinner(spinner)

  const serverPayload = {
    type: "user_message",
    command,
    content: cleanPrompt,
    model: selectedModel,
    projectId: path.basename(process.cwd()),
    cwd: process.cwd(),
    sysbasePath: getSysbasePath(),
    directoryTree: dirTree,
    mentionedFiles,
    chatUid: chatUid || undefined,
    planMode,
    client: { platform: os.platform(), arch: os.arch() }
  }

  let response: Record<string, unknown>
  const budget: RetryBudget = makeRetryBudget()

  // Wrap callServerStream / callServer in a single retryable call. USAGE_LIMIT bubbles up.
  async function makeServerCall(payload: Record<string, unknown>, phaseHandler?: (label: string) => void): Promise<Record<string, unknown>> {
    try {
      return await callServerStream(payload, phaseHandler)
    } catch (err) {
      if ((err as ServerError).code === "USAGE_LIMIT") throw err
      return await callServer(payload)
    }
  }

  // ─── Initial call with task-driven retry on rate/usage limits ───
  let initialAttempts = 0
  const MAX_INITIAL_ATTEMPTS = 6
  while (true) {
    try {
      response = await makeServerCall(serverPayload, (label) => {
        spinner.text = colors.muted(suppressGenericPhaseLabel(label))
      })
      break
    } catch (err) {
      if ((err as ServerError).code === "USAGE_LIMIT" && initialAttempts < MAX_INITIAL_ATTEMPTS) {
        initialAttempts++
        const waitMs = Math.min(5000 * Math.pow(2, initialAttempts - 1), 120_000)
        spinner.stop()
        console.log("")
        console.log(colors.warning(`  ⚠ Usage limit hit — waiting ${Math.round(waitMs / 1000)}s before retry (${initialAttempts}/${MAX_INITIAL_ATTEMPTS})`))
        console.log(colors.muted("    The system will reduce usage and retry automatically."))
        await sleep(waitMs)
        spinner.start(colors.muted("retrying..."))
        continue
      }
      if ((err as ServerError).code === "USAGE_LIMIT") {
        spinner.stop()
        console.log("")
        console.log(colors.warning("  ⚠ " + (err as Error).message))
        console.log(colors.muted("  Exhausted all retry attempts."))
        console.log(colors.muted("  Run ") + colors.accent("sys billing") + colors.muted(" to upgrade your plan"))
        console.log("")
        return
      }
      spinner.stop()
      throw err
    }
  }

  // Phase 5: render the pre-flight reasoning brief if the server returned one.
  if (response.reasoningBrief) {
    spinner.stop()
    // Phase 14 Stage 4: in Ink mode the brief is surfaced as a structured
    // <ReasoningPeek> via the events bus. The legacy ASCII-box renderer
    // (renderReasoningBrief in cli/reasoning-display.ts) prints chrome
    // that would render as raw `┌── REASONING ──┐` text inside the
    // AgentStream log if it ran in Ink mode.
    if (shouldRenderInlineForLegacy()) {
      renderReasoningBrief(response.reasoningBrief)
    } else {
      const brief = response.reasoningBrief as Record<string, unknown>
      const kind = typeof brief.pipeline === "string" ? brief.pipeline : "unknown"
      emitAgent({ type: "reasoning_brief", kind, briefData: brief })
    }
    spinner.start(colors.muted("thinking..."))
  }
  // Phase 16 Stage 3 / Phase 16-fixup (Bug 3): when the chained elaboration
  // brief comes back on the response, surface it via ReasoningPeek too so
  // the user can see WHY the agent picked the chosen approach.
  const reasoningElaborationBrief = (response as Record<string, unknown>).reasoningElaborationBrief
  if (reasoningElaborationBrief && isInkActive()) {
    emitAgent({ type: "reasoning_brief", kind: "implement_elaborate", briefData: reasoningElaborationBrief as Record<string, unknown> })
  }

  let stepCount = 0
  let taskShown = false
  let taskSteps: Array<{ id: string; label: string; status?: string }> = []
  const completedSteps = new Set<string>()
  let lastDisplayedAction: string | null = null
  let lastDisplayedReasoning: string | null = null
  // Phase 10: track which chunk index we're rendering so the badge increments
  // monotonically across turns (server doesn't send the index — it's implicit
  // in the order chunkPlanBrief arrives).
  let chunkIndex = 0
  // Phase 10: telemetry counters. Each successful brief observed = one
  // successful Flash call. Failed Flash calls don't produce briefs so they
  // aren't counted (intentional — telemetry is best-effort, not auditable).
  let flashCallsCount = 0
  if ((response as Record<string, unknown>).reasoningBrief) flashCallsCount += 1
  // Stage 5 of command-first-investigation: per-run telemetry of how
  // many safe-read-only `run_command` calls the agent dispatched.
  // Counted at the CLI dispatch site (both single-tool and batch paths)
  // inside `handleNeedsTool`, threaded back via NeedsToolResult.
  let investigationCommandsCount = 0
  // Stage E of model-lock-and-portable-reasoning: capture the resolved
  // reasoner backend the FIRST time it lands on a server response (it's
  // constant for the rest of the run). Recorded into RunSummary on
  // terminal exit so usage.jsonl gets the field.
  let reasonerBackend: "gemini" | "anthropic" | "openrouter" | null = null
  const initialBackend = (response as Record<string, unknown>).reasonerBackend
  if (initialBackend === "gemini" || initialBackend === "anthropic" || initialBackend === "openrouter") {
    reasonerBackend = initialBackend
  }
  // Phase 19: capture the classified intent on the initial response.
  // Held in `runIntent` for the lifetime of the run; emitted to the
  // event bus so the useAgentEvents reducer + <AgentStream> can gate
  // the task box (only `implement` runs render the box; Q&A / summary /
  // bug pipelines stay lean — see plan
  // `applied/2026-05-07-phase-19-task-display-selectivity.md`).
  let runIntent: "simple" | "summary" | "bug" | "implement" | null = null
  const initialIntent = (response as Record<string, unknown>).runIntent
  if (initialIntent === "simple" || initialIntent === "summary" || initialIntent === "bug" || initialIntent === "implement") {
    runIntent = initialIntent
    emitAgent({ type: "intent_classified", intent: initialIntent })
  }
  // Stage 5 of llm-iterative-intent-classification: capture the
  // classification source for usage.jsonl telemetry. First-observation
  // wins; constant for the rest of the run since the cache holds it.
  // Stage 3 of speed-overhaul plan (2026-05-20): added "regex_confident"
  // — emitted when the regex matched a SPECIFIC pattern
  // (IMPLEMENT_LEAD / BUG / SUMMARY) and the LLM chain was skipped.
  let intentClassificationSource: "cache" | "regex_simple" | "regex_confident" | "regex_fallback" | "chain" | null = null
  const initialSource = (response as Record<string, unknown>).intentClassificationSource
  if (
    initialSource === "cache"
    || initialSource === "regex_simple"
    || initialSource === "regex_confident"
    || initialSource === "regex_fallback"
    || initialSource === "chain"
  ) {
    intentClassificationSource = initialSource
  }
  // Stage 5: when the LLM iterative chain produced paragraphs, emit
  // them as a `reasoning_brief` event so <ReasoningPeek>'s plain-prose
  // render path (PR #83) surfaces the senior-engineer reasoning to
  // the user. Same mechanism the other reasoning briefs use; no new
  // renderer needed.
  const initialChainParagraphs = (response as Record<string, unknown>).intentClassificationParagraphs
  if (Array.isArray(initialChainParagraphs) && initialChainParagraphs.length > 0) {
    const paragraphs = initialChainParagraphs.filter((p): p is string => typeof p === "string" && p.trim().length > 0)
    if (paragraphs.length > 0) {
      emitAgent({ type: "reasoning_brief", kind: "intent_classification", briefData: { reasoningChain: paragraphs } })
    }
  }
  // Stage 3 of forced-error-reasoning plan: same shape but for
  // error-reasoning paragraphs on the initial response (rare path —
  // user-message.ts doesn't currently fire on_error, but defensive).
  const initialErrorParagraphs = (response as Record<string, unknown>).errorReasoningParagraphs
  if (Array.isArray(initialErrorParagraphs) && initialErrorParagraphs.length > 0) {
    const paragraphs = initialErrorParagraphs.filter((p): p is string => typeof p === "string" && p.trim().length > 0)
    if (paragraphs.length > 0) {
      emitAgent({ type: "reasoning_brief", kind: "error_reasoning", briefData: { reasoningChain: paragraphs } })
    }
  }
  // Stage 1 of agent-runtime-fixes plan: project-init paragraphs.
  // Surfaces the repo-state classification + investigation plan in
  // the peek (via the plain-prose render path) so the user sees the
  // very first thing the agent reasoned about — what kind of repo
  // we're in. Constant for the run; emitted ONCE here on the first
  // response.
  const projectInitParagraphs = (response as Record<string, unknown>).projectInitParagraphs
  if (Array.isArray(projectInitParagraphs) && projectInitParagraphs.length > 0) {
    const paragraphs = projectInitParagraphs.filter((p): p is string => typeof p === "string" && p.trim().length > 0)
    if (paragraphs.length > 0) {
      emitAgent({ type: "reasoning_brief", kind: "project_init", briefData: { reasoningChain: paragraphs } })
    }
  }
  const initialErrorSource = (response as Record<string, unknown>).errorReasoningSource
  // Stage 3 of forced-error-reasoning plan: track the LATEST error-
  // reasoning source observed this run (most recent wins, since
  // different error turns may take different paths).
  let errorReasoningSourceLatest: "chain" | "bug_fallback" | null = null
  if (initialErrorSource === "chain" || initialErrorSource === "bug_fallback") {
    errorReasoningSourceLatest = initialErrorSource
  }
  // Stage 6: per-run counters surfaced in RunSummary so usage.jsonl
  // reflects how often error-reasoning fired and the peak number of
  // ack-rejections any single error triggered.
  let errorReasoningEventsThisRun = 0
  if (initialErrorSource === "chain" || initialErrorSource === "bug_fallback") {
    errorReasoningEventsThisRun = 1
  }
  let errorAckRejectionsPeak = 0
  const initialAckCount = (response as Record<string, unknown>).errorAckRejectionCount
  if (typeof initialAckCount === "number" && initialAckCount > 0) {
    errorAckRejectionsPeak = initialAckCount
  }
  // Stage 5 of agent-runtime-fixes plan: capture the project-init
  // classification from the initial response (constant for the run).
  // Surface the brief + confidence + repoState — three RunSummary
  // fields. Null sentinel when the chain didn't fire (legacy / flag
  // off / no reasoner backend).
  let projectInitRepoState: "empty" | "small" | "existing-small" | "existing-large" | null = null
  let projectInitConfidence: "HIGH" | "MEDIUM" | "LOW" | null = null
  {
    const repo = (response as Record<string, unknown>).projectInitRepoState
    if (repo === "empty" || repo === "small" || repo === "existing-small" || repo === "existing-large") {
      projectInitRepoState = repo
    }
    const conf = (response as Record<string, unknown>).projectInitConfidence
    if (conf === "HIGH" || conf === "MEDIUM" || conf === "LOW") {
      projectInitConfidence = conf
    }
  }
  // Stage 5: per-run count of 0-hit web_search results. Bumped each
  // time the cli observes a tool_result with `_errorCategory:
  // "web_search_empty"`.
  let webSearchEmptyCount = 0
  // Stage 5 of server-hardening plan: per-run counter for sysflow_infra
  // terminal failures. 0 or 1 per run (sysflow_infra halts the loop).
  let sysflowInfraErrorCount = 0
  // Stage 5 of code-correctness plan: completion-gate counters.
  // tscErrorCount: peak observed across the run (max-wins so a brief
  // recovery doesn't undercount). completionBlockedReason: last-write
  // wins (which gate blocked LAST).
  let tscErrorCountPeak = 0
  let completionBlockedReasonLatest: "tsc" | "artifact_missing" | null = null
  // Stage 5 of awareness-and-verification-correctness plan: telemetry.
  // intentKeywordContentMatches: server-side cumulative count, peak
  // captured client-side (max-wins). awarenessModalShown: latched true
  // when Stage 3's off-course modal renders.
  let intentKeywordContentMatchesPeak = 0
  let awarenessModalShownThisRun = false
  // Stage 6 of accountability-and-parallel-execution-sequencing plan:
  // peak observed batch size (tools.length across all turns) +
  // server-side insufficient-reasoning rejection peak.
  let maxBatchSizeObserved = 0
  let insufficientReasoningRejectionPeak = 0
  // Stage 6 of ui-ux-polish plan: latch for the sysflow_infra
  // structured-banner path. Module-level latches in use-frame.ts /
  // spinner-label-format.ts / tools.ts / permission-prompt.ts cover
  // the other Stage 6 counters; this one lives on the agent state
  // because it's set inline at the terminal-exit path below.
  let infraErrorBannerShownThisRun = false
  // Stage 4 of reasoning-chain-provider-parity plan: distribution
  // counters for structured-vs-synthesised per-turn reasoning. Bumped
  // each turn based on the server-side classification surfaced on
  // ClientResponse.perTurnReasoningSource. High synthesised share over
  // time = directive being ignored = tighten Stage 2's prompt or add
  // model-specific shim.
  let reasoningChainEmittedTurns = 0
  let reasoningChainSynthesisedTurns = 0
  {
    const sourceInitial = (response as Record<string, unknown>).perTurnReasoningSource
    if (sourceInitial === "structured") reasoningChainEmittedTurns += 1
    else if (sourceInitial === "synthesised") reasoningChainSynthesisedTurns += 1
  }
  // Resolve the task-display-selective flag once for the run — toggling
  // mid-run isn't a supported flow.
  const taskDisplaySelective = await getTaskDisplaySelective()
  // Phase 11 Stage 5: track the last awareness state we've shown so we can
  // emit a one-line transition log when the badge flips
  // (on_track → off_course or off_course → blocked).
  let lastAwarenessState: "on_track" | "off_course" | "blocked" | null = null
  // Phase 11 Stage 6: per-run awareness telemetry. Three counters land in
  // recordRunSummary on terminal exit so the JSONL can be diffed across
  // versions to spot regressions in the awareness loop's noise level.
  let divergenceDetectionsThisRun = 0
  let confidenceSampleSum = 0
  let confidenceSampleCount = 0
  let autoPauseEventsThisRun = 0
  /** Inline helper: tally a snapshot for the per-run telemetry counters.
   *  Counts a "detection" only on the FIRST < 100 sample per chunk so we
   *  don't double-count when a chunk emits multiple snapshots. */
  let lastSampledChunkIndex = -1
  function tallyAwareness(snap: { state: string; confidence: number } | undefined): void {
    if (!snap) return
    confidenceSampleSum += snap.confidence
    confidenceSampleCount += 1
    if (snap.confidence < 100 && lastSampledChunkIndex !== chunkIndex) {
      divergenceDetectionsThisRun += 1
      lastSampledChunkIndex = chunkIndex
    }
  }
  // Phase 10: initial-turn chunk plan from user-message.ts
  if ((response as Record<string, unknown>).chunkPlanBrief) {
    spinner.stop()
    chunkIndex = 1
    flashCallsCount += 1
    const initialAwareness = (response as Record<string, unknown>).awarenessSnapshot as { state: "on_track" | "off_course" | "blocked"; confidence: number; lastSignal?: string | null } | undefined
    const initialPlan = (response as Record<string, unknown>).chunkPlanBrief as { nextAction?: string; files?: string[] } | undefined
    renderChunkProgress({
      chunkIndex,
      plan: initialPlan as never,
      reflection: null,
      awareness: initialAwareness ?? null,
    })
    if (initialAwareness) {
      lastAwarenessState = initialAwareness.state
      tallyAwareness(initialAwareness)
    }
    // Phase 12 Stage 5: surface the chunk-plan + awareness to the Ink Header.
    // Plan 2026-05-18-chunk-pulse-missing-diagnostic.md Stage 2 — emit
    // decision routed through the pure `chunkPlanEventFromResponse`
    // helper so both observer sites are symmetric and integration-
    // testable.
    const initialChunkEvent = chunkPlanEventFromResponse(
      response as Record<string, unknown>,
      chunkIndex,
      isInkActive(),
    )
    if (initialChunkEvent) emitAgent(initialChunkEvent)
    if (isInkActive() && initialAwareness) {
      emitAgent({
        type: "awareness_update",
        state: initialAwareness.state,
        confidence: initialAwareness.confidence,
        lastSignal: initialAwareness.lastSignal ?? null,
      })
    }
    spinner.start(colors.muted("thinking..."))
  }
  const currentRunId = (response.runId as string) || ""
  // Phase 11 Stage 2: snapshot the working tree before the first chunk's
  // tools execute, so a Stage 4 backtrack can roll back to the pre-chunk-1
  // state. Best-effort — failures degrade gracefully (rollback simply isn't
  // available for this run). Awaited so the snapshot is in place before the
  // executor dispatches the next tool batch.
  if ((response as Record<string, unknown>).chunkPlanBrief && currentRunId) {
    try { await createChunkSnapshot(process.cwd(), currentRunId, 1) } catch { /* best-effort */ }
  }
  let lastPipelineStepId: string | null = null
  let prevTool: string | null = null  // for read-coalescing in handleNeedsTool

  // ─── Usage telemetry: tally counters during the run ───
  const startedAtMs = Date.now()
  let toolCount = 0
  let errorCount = 0
  const inputTokens = cliEstimateTokens(serverPayload)
  let outputTokens = 0

  const cleanupDiffListener = startDiffKeyListener(spinner)

  // Phase 7: pinned bottom-row indicator for background jobs (e.g. npm install).
  // Phase 16-fixup: the job-status bar uses raw cursor-save/restore + bottom-row
  // writes which collide with Ink's reserved region — that's part of Bug 4 (the
  // scroll bug). LiveStatusBar already shows working/elapsed in Ink mode, so
  // gate this behind legacy mode.
  if (currentRunId && shouldRenderInlineForLegacy()) startJobStatusBar(currentRunId)

  const recordTelemetry = async (terminalReason: string): Promise<void> => {
    // Phase 7: wait up to 30s for outstanding background jobs, then SIGTERM the rest.
    let bgJobsRun = 0
    let bgJobsFailed = 0
    if (currentRunId) {
      const allJobs = listBackgroundJobs(currentRunId)
      bgJobsRun = allJobs.length
      try {
        const cleanupResult = await cleanupBackgroundJobs(currentRunId)
        // Re-poll to get final statuses after cleanup.
        const finalJobs = listBackgroundJobs(currentRunId)
        bgJobsFailed = finalJobs.filter((j) => j.status === "failed").length
        if (cleanupResult.aborted > 0) {
          console.log(colors.warning(`  ⚠ ${cleanupResult.aborted} background job(s) aborted on exit (exceeded 30s wait window)`))
        }
      } catch { /* best-effort */ }
      if (shouldRenderInlineForLegacy()) stopJobStatusBar()
      // Phase 11 Stage 2: drop chunk snapshot tags so they don't pile up
      // across runs in the user's repo. Stash refs are already popped in
      // createChunkSnapshot; only tag-strategy snapshots leave a trace.
      try { await cleanupChunkSnapshots(process.cwd(), currentRunId) } catch { /* best-effort */ }
    }
    await recordRunSummary(getSysbasePath(), {
      runId: currentRunId || null,
      prompt: cleanPrompt,
      model: selectedModel,
      durationMs: Date.now() - startedAtMs,
      stepCount,
      toolCount,
      errorCount,
      estimatedInputTokens: inputTokens,
      estimatedOutputTokens: outputTokens,
      terminalReason,
      backgroundJobsRun: bgJobsRun,
      backgroundJobsFailed: bgJobsFailed,
      chunkCount: chunkIndex,
      flashCallsCount,
      divergenceDetections: divergenceDetectionsThisRun,
      divergenceConfidenceAvg: confidenceSampleCount > 0 ? confidenceSampleSum / confidenceSampleCount : undefined,
      autoPauseEvents: autoPauseEventsThisRun,
      reasonerBackend,
      investigationCommandsCount,
      intentClassificationSource,
      errorReasoningSource: errorReasoningSourceLatest,
      errorReasoningEvents: errorReasoningEventsThisRun,
      errorAcknowledgementRejections: errorAckRejectionsPeak,
      projectInitRepoState,
      projectInitConfidence,
      webSearchEmptyCount,
      reasoningPeekExpansions: getReasoningPeekExpansions(),
      reasoningChainEmittedTurns,
      reasoningChainSynthesisedTurns,
      // Stage 5 of server-hardening plan: read module-level counters
      // (bumped from executor.ts + server.ts on each rejection).
      sysflowInfraErrorCount,
      nullToolRejectionCount: getNullToolRejections(),
      nonRetryable5xxCount: getNonRetryable5xxCount(),
      // Stage 5 of code-correctness plan: import strips (cli-side),
      // tsc error peak + completion-blocked reason (server-side
      // surfaced via ClientResponse).
      importsStrippedCount: getImportsStrippedCount(),
      tscErrorCount: tscErrorCountPeak,
      completionBlockedReason: completionBlockedReasonLatest,
      // Stage 5 of awareness-and-verification-correctness plan.
      dotfileFilterCorrections: getDotfileFilterCorrections(),
      intentKeywordContentMatches: intentKeywordContentMatchesPeak,
      awarenessModalShown: awarenessModalShownThisRun,
      windowsShellErrorsCaught: getWindowsShellErrorsCaught(),
      // Stage 6 of accountability-and-parallel-execution-sequencing plan.
      maxBatchSize: maxBatchSizeObserved,
      batchCapEnforcedCount: getBatchCapEnforcedCount(),
      reorderedBatchCount: getBatchReorderedCount(),
      alreadyCreatedRejectionCount: getAlreadyCreatedRejectionCount(),
      insufficientReasoningRejectionCount: insufficientReasoningRejectionPeak,
      // Stage 6 of ui-ux-polish plan.
      scrollGlitchPauseFiredCount: getScrollGlitchPauseFiredCount(),
      spinnerActionLabelFired: getSpinnerActionLabelFired(),
      streamPreviewEverShown: getStreamPreviewEverShown(),
      infraErrorBannerShown: infraErrorBannerShownThisRun,
      permissionModalShownCount: getPermissionModalShownCount(),
    })
    resetReasoningPeekExpansions()
    resetNullToolRejections()
    resetNonRetryable5xxCount()
    resetImportsStrippedCount()
    // Stage 5 of awareness-and-verification-correctness plan.
    resetDotfileFilterCorrections()
    resetWindowsShellErrorsCaught()
    // Stage 4 of accountability-and-parallel-execution-sequencing plan.
    resetAlreadyCreatedRejectionCount()
    if (currentRunId) clearCreatedPaths(currentRunId)
    // Stage 6 of accountability-and-parallel-execution-sequencing plan.
    resetBatchCapEnforcedCount()
    resetBatchReorderedCount()
    // Stage 6 of ui-ux-polish plan: reset the per-run telemetry latches.
    resetScrollGlitchPauseFiredCount()
    resetSpinnerActionLabelFired()
    resetStreamPreviewEverShown()
    resetPermissionModalShownCount()
    unregisterSpinner()
  }

  while (true) {
    // Safety: detect misclassified responses — "completed" but message contains needs_tool JSON
    if (response.status === "completed") {
      const msg = (response.message || response.content || "") as string
      if (msg.trimStart().startsWith("{")) {
        try {
          const parsed = JSON.parse(msg)
          if (parsed.kind === "needs_tool" && (parsed.tool || parsed.tools)) {
            response.status = "needs_tool"
            response.tool = parsed.tool || undefined
            response.args = parsed.args || undefined
            if (parsed.args_json) {
              try { response.args = typeof parsed.args_json === "string" ? JSON.parse(parsed.args_json) : parsed.args_json } catch { /* ignore */ }
            }
            if (Array.isArray(parsed.tools)) {
              response.tools = parsed.tools.map((tc: Record<string, unknown>, i: number) => {
                let args: Record<string, unknown> = {}
                if (tc.args_json) {
                  try { args = typeof tc.args_json === "string" ? JSON.parse(tc.args_json as string) : tc.args_json as Record<string, unknown> } catch { /* */ }
                } else if (tc.args) {
                  args = tc.args as Record<string, unknown>
                }
                return { id: (tc.id as string) || `tc_${i}`, tool: tc.tool as string, args }
              })
            }
            response.reasoning = parsed.reasoning || null
            response.content = parsed.content || null
            response.message = null
          }
        } catch { /* not JSON */ }
      }
    }

    const transition = classifyResponse(response)

    // ─── Client-side completion verification: reject premature completion ───
    if (transition.terminal && transition.reason === "completed") {
      const completionMsg = ((response.message || response.content || "") as string).toLowerCase()
      const isComplexPrompt = /full[- ]?stack|backend.*frontend|multiple\s+modules|end[- ]?to[- ]?end|crud.*auth|nestjs.*next/i.test(prompt)
      const isShortCompletion = completionMsg.length < 150
      const hasListedFiles = /files?\s*(created|modified|written)/i.test(completionMsg)
      const tooFewSteps = stepCount < 5 && isComplexPrompt

      if (
        isComplexPrompt
        && (tooFewSteps || (isShortCompletion && !hasListedFiles))
        && response.runId
        && budget.completion_rejection.used < budget.completion_rejection.max
      ) {
        budget.completion_rejection.used++
        spinner.stop()
        console.log("")
        console.log(colors.warning(`  ⚠ Task appears incomplete (${stepCount} steps for a complex task)`))
        console.log(colors.muted(`    Auto-continuing... (attempt ${budget.completion_rejection.used}/${budget.completion_rejection.max})`))
        console.log("")
        spinner.start(colors.muted("continuing task..."))

        try {
          response = await makeServerCall({
            type: "tool_result",
            runId: response.runId,
            tool: "_completion_rejected",
            result: {
              error: `CLIENT REJECTION: The task is complex but only ${stepCount} steps were taken. Continue implementing all required files before completing.`,
              success: false,
              originalTask: prompt,
              hint: "Respond with needs_tool to continue. Do NOT respond with completed again until ALL files are created."
            }
          }, (label) => { spinner.text = colors.muted(suppressGenericPhaseLabel(label)) })
        } catch {
          response = await callServer({
            type: "tool_result",
            runId: response.runId,
            tool: "_completion_rejected",
            result: { error: "Task incomplete. Continue implementing.", success: false, originalTask: prompt }
          })
        }
        continue
      }
    }

    // ─── Handle terminal transitions ───
    if (transition.terminal) {
      switch (transition.reason) {
        case "completed": {
          spinner.stop()
          await renderCompletion(response, hasReasoning, lastDisplayedReasoning, taskSteps, completedSteps, stepCount)
          cleanupDiffListener()
          disableDiffExpand()
          if (currentRunId) clearRunDiffs(currentRunId)
          outputTokens = cliEstimateTokens(response.message || response.content || "")
          await recordTelemetry("completed")
          return response
        }
        case "session_expired": {
          spinner.stop()
          console.log("")
          console.log(colors.warning("  Session expired (server was restarted)."))
          console.log(colors.muted("  Run your prompt again with ") + colors.accent("sys \"your prompt\"") + colors.muted(" or ") + colors.accent("sys continue"))
          console.log("")
          cleanupDiffListener()
          await recordTelemetry("session_expired")
          return response
        }
        case "prompt_too_long": {
          spinner.stop()
          console.log("")
          console.log(colors.warning("  ⚠ " + ((response.error as string) || "Prompt too long")))
          console.log(colors.muted("  Try a shorter prompt or fewer @file mentions, or run ") + colors.accent("sys chat new") + colors.muted(" to start fresh."))
          console.log("")
          cleanupDiffListener()
          await recordTelemetry("prompt_too_long")
          return response
        }
        case "malformed_response_exhausted": {
          spinner.stop()
          console.log("")
          console.log(colors.error("  ✖ Model returned malformed JSON repeatedly. Aborting."))
          console.log(colors.muted("  " + ((response.error as string) || "")))
          console.log("")
          cleanupDiffListener()
          await recordTelemetry("malformed_response_exhausted")
          throw new Error((response.error as string) || "malformed_response")
        }
        case "sysflow_infra": {
          // Stage 2 of plan 2026-05-16-server-hardening-and-error-source-distinction.md.
          // Sysflow's own backend / API quota / auth / connection
          // failed. The agent CANNOT recover from inside the loop —
          // user action required (top up credits, /model swap, set
          // env var). Halt cleanly with a distinct banner so the user
          // doesn't confuse it with a project-side error.
          //
          // Stage 4 of plan 2026-05-18-ui-ux-polish-and-action-aware-spinner.md
          // (audit issue #1): emit a structured `infra_error` event so
          // <AgentStream> can render an <ErrorBanner> in the live region.
          // Pre-Stage-4 the cli wrote 5+ raw console.log lines here — same
          // gotcha-104 risk class as raw cursor-up writes. Legacy mode
          // (shouldRenderInlineForLegacy() === true) still uses the
          // inline path so terminals without Ink stay readable.
          sysflowInfraErrorCount = 1
          spinner.stop()
          const errorMsg = (response.error as string) || "Unspecified sysflow backend failure"
          const hint = "This is a sysflow / API provider issue — not a problem with your project. Take the suggested action and re-run. The agent will NOT try to 'fix' this from inside your project."
          if (shouldRenderInlineForLegacy()) {
            console.log("")
            console.log(colors.error("  ═══ SYSFLOW INFRASTRUCTURE ERROR ═══"))
            console.log(colors.warning("  " + errorMsg))
            console.log("")
            console.log(colors.muted("  " + hint))
            console.log(colors.error("  ═══════════════════════════════════"))
            console.log("")
          } else {
            emitAgent({
              type: "infra_error",
              title: "SYSFLOW INFRASTRUCTURE ERROR",
              message: errorMsg,
              hint,
            })
            // Stage 6 of plan 2026-05-18-ui-ux-polish-and-action-aware-spinner.md:
            // latch — used by RunSummary to mark this run as having
            // surfaced the structured infra-error banner.
            infraErrorBannerShownThisRun = true
          }
          cleanupDiffListener()
          await recordTelemetry("sysflow_infra")
          return response
        }
        default: {
          spinner.stop()
          cleanupDiffListener()
          disableDiffExpand()
          if (currentRunId) clearRunDiffs(currentRunId)
          await recordTelemetry(transition.reason)
          throw new Error(`Unexpected terminal: ${transition.reason}`)
        }
      }
    }

    // ─── Continue transitions ───
    switch (transition.reason) {
      case "tool_executed":
      case "tool_batch_executed": {
        toolCount += transition.reason === "tool_batch_executed" ? Math.max(1, ((response.tools as unknown[]) || []).length) : 1
        const result = await handleNeedsTool(
          response,
          spinner,
          { hasReasoning, lastDisplayedAction, lastDisplayedReasoning, currentRunId, taskShown, taskSteps, completedSteps, lastPipelineStepId, prevTool, chunkIndex, flashCallsThisTurn: 0, lastAwarenessState, runIntent, taskDisplaySelective, budget, projectInitRepoState },
          makeServerCall,
        )
        response = result.response
        stepCount = result.stepCount === undefined ? stepCount + 1 : stepCount + result.stepCount
        taskShown = result.taskShown
        taskSteps = result.taskSteps
        lastDisplayedAction = result.lastDisplayedAction
        lastDisplayedReasoning = result.lastDisplayedReasoning
        lastPipelineStepId = result.lastPipelineStepId
        prevTool = result.toolThisTurn
        chunkIndex = result.chunkIndex
        flashCallsCount += result.flashCallsThisTurn
        investigationCommandsCount += result.investigationCommandsThisTurn
        webSearchEmptyCount += result.webSearchEmptyThisTurn
        if (result.perTurnReasoningSourceThisTurn === "structured") reasoningChainEmittedTurns += 1
        else if (result.perTurnReasoningSourceThisTurn === "synthesised") reasoningChainSynthesisedTurns += 1
        // Phase 19: defensive capture of runIntent from subsequent
        // responses in case the initial response didn't carry it.
        // Once set, stays set — the value is run-constant.
        if (!runIntent) {
          const next = (response as Record<string, unknown>).runIntent
          if (next === "simple" || next === "summary" || next === "bug" || next === "implement") {
            runIntent = next
            emitAgent({ type: "intent_classified", intent: next })
          }
        }
        lastAwarenessState = result.lastAwarenessState
        // Phase 11 Stage 6: tally the awareness snapshot from this turn into
        // the per-run telemetry counters (recorded on terminal exit).
        tallyAwareness((response as Record<string, unknown>).awarenessSnapshot as { state: string; confidence: number } | undefined)
        if ((response as Record<string, unknown>).awarenessChoice === true) {
          autoPauseEventsThisRun += 1
          // Stage 5 of awareness-and-verification-correctness plan:
          // latch the modal-shown flag so the per-run telemetry records
          // it even if the user picks "continue" and the run keeps going.
          awarenessModalShownThisRun = true
        }
        // Stage 5: peak-wins capture for server-side cumulative
        // intent-match count. Server's counter is monotonic per run;
        // taking the max is defensive against an out-of-order response.
        const intentMatches = (response as Record<string, unknown>).intentKeywordContentMatches
        if (typeof intentMatches === "number" && intentMatches > intentKeywordContentMatchesPeak) {
          intentKeywordContentMatchesPeak = intentMatches
        }
        // Stage 6 of accountability-and-parallel-execution-sequencing
        // plan: peak-wins capture for the server-side
        // per-file-reasoning rejection counter.
        const pfRejections = (response as Record<string, unknown>).insufficientReasoningRejectionCount
        if (typeof pfRejections === "number" && pfRejections > insufficientReasoningRejectionPeak) {
          insufficientReasoningRejectionPeak = pfRejections
        }
        // Stage 6: track the maximum tools[] batch size observed.
        // Inspects the response from the just-completed turn so the
        // wide-batch pattern shows up in telemetry even when Stage 1's
        // cli-side cap deferred the tail.
        const responseTools = (response as Record<string, unknown>).tools
        if (Array.isArray(responseTools) && responseTools.length > maxBatchSizeObserved) {
          maxBatchSizeObserved = responseTools.length
        }
        // Stage 3 of forced-error-reasoning plan: when a turn's response
        // carries `errorReasoningParagraphs`, emit a reasoning_brief
        // event so <ReasoningPeek>'s plain-prose render path (PR #83)
        // surfaces the LLM's error analysis to the user. Without this
        // the chain paragraphs are invisible — same root-cause-of-
        // gloss-over the plan was designed to fix.
        const errorReasoningParagraphs = (response as Record<string, unknown>).errorReasoningParagraphs
        if (Array.isArray(errorReasoningParagraphs) && errorReasoningParagraphs.length > 0) {
          const paragraphs = errorReasoningParagraphs.filter((p): p is string => typeof p === "string" && p.trim().length > 0)
          if (paragraphs.length > 0) {
            emitAgent({ type: "reasoning_brief", kind: "error_reasoning", briefData: { reasoningChain: paragraphs } })
          }
        }
        // Stage 3 of agent-runtime-fixes plan: emit the per-turn
        // reasoningChain as a `reasoning_brief` event so the peek tracks
        // the LATEST deliberation, not just the first brief of the run.
        // Closes bug 6 (peek stuck on initial brief while the agent
        // iterated through later tools).
        const perTurnChain = (response as Record<string, unknown>).perTurnReasoningChain
        if (Array.isArray(perTurnChain) && perTurnChain.length > 0) {
          const paragraphs = perTurnChain.filter((p): p is string => typeof p === "string" && p.trim().length > 0)
          if (paragraphs.length > 0) {
            emitAgent({ type: "reasoning_brief", kind: "per_turn", briefData: { reasoningChain: paragraphs } })
          }
        }
        // Stage 3: track the LATEST error-reasoning source seen this run.
        // Last-write-wins (mirrors the per-error trigger — every error
        // turn may have a different source; the most recent is the
        // most informative for telemetry).
        const ers = (response as Record<string, unknown>).errorReasoningSource
        if (ers === "chain" || ers === "bug_fallback") {
          errorReasoningSourceLatest = ers
          // Stage 6: count every observation as one "error reasoning
          // event" — captures both chain commits and bug-fallback paths
          // for the per-run RunSummary.
          errorReasoningEventsThisRun += 1
        }
        // Stage 6: capture peak Stage 4 rejection count for telemetry.
        // Server surfaces a running count; we keep the max so a brief
        // server hiccup that resets the counter doesn't undercount.
        const ackCount = (response as Record<string, unknown>).errorAckRejectionCount
        if (typeof ackCount === "number" && ackCount > errorAckRejectionsPeak) {
          errorAckRejectionsPeak = ackCount
        }
        // Stage 5 of code-correctness plan: capture completion-gate
        // override signals. Server attaches completionBlockedBy when
        // tsc gate (Stage 3) or artifact gate (Stage 4) overrode a
        // completed response. Peak tsc error count for tsc gate.
        const blockedBy = (response as Record<string, unknown>).completionBlockedBy
        if (blockedBy === "tsc" || blockedBy === "artifact_missing") {
          completionBlockedReasonLatest = blockedBy
        }
        const tscErr = (response as Record<string, unknown>).completionTscErrorCount
        if (typeof tscErr === "number" && tscErr > tscErrorCountPeak) {
          tscErrorCountPeak = tscErr
        }
        // Stage E of model-lock-and-portable-reasoning: capture the
        // backend if it wasn't surfaced on the very first response
        // (preflight didn't run, or this is a /continue run where the
        // initial response was a cache hit). Constant once set.
        if (!reasonerBackend) {
          const b = (response as Record<string, unknown>).reasonerBackend
          if (b === "gemini" || b === "anthropic" || b === "openrouter") {
            reasonerBackend = b
          }
        }
        noteSuccess(budget)
        break
      }

      case "user_responded": {
        spinner.stop()

        // ─── Phase 11 Stage 4: off-course modal hijacks the generic prompt ───
        // The server attaches `awarenessChoice: true` + evidence when
        // confidence drops past awareness.threshold_blocked. Render the
        // dedicated 3-key modal instead of the generic free-text askUser.
        const awarenessChoice = (response as Record<string, unknown>).awarenessChoice === true
        if (awarenessChoice && currentRunId) {
          const evidence = ((response as Record<string, unknown>).awarenessEvidence ?? {}) as OffCourseEvidence
          const choice = await askOffCourse(evidence)
          // Backtrack: roll the working tree back to the snapshot taken at
          // the start of the chunk that crossed the threshold.
          if (choice.action === "backtrack") {
            try {
              const ok = await rollbackToChunk(process.cwd(), currentRunId, evidence.lastGoodChunkIndex)
              if (!ok) console.log(colors.warning(`  ⚠ rollback didn't find a snapshot for chunk ${evidence.lastGoodChunkIndex} — keeping current state`))
            } catch (rollbackErr) {
              console.log(colors.warning(`  ⚠ rollback failed: ${(rollbackErr as Error).message}`))
            }
          }
          spinner.start(colors.muted("thinking..."))
          response = await makeServerCall({
            type: "tool_result",
            runId: currentRunId,
            tool: "_user_response",
            result: {
              kind: "off_course",
              action: choice.action,
              text: choice.text ?? null,
              lastGoodChunkIndex: evidence.lastGoodChunkIndex,
              success: true,
            },
          }, (label) => { spinner.text = colors.muted(suppressGenericPhaseLabel(label)) })
          break
        }

        console.log("")
        const questionText = (response.message || response.content || "Waiting for your input") as string
        const renderedQ = renderMarkdown(questionText)
        for (const qLine of renderedQ.split("\n")) {
          console.log("  " + boxMid(qLine, 50))
        }
        console.log("")

        const userAnswer = await askUser(questionText)

        if (!userAnswer || userAnswer.toLowerCase() === "quit" || userAnswer.toLowerCase() === "exit") {
          console.log(colors.muted("  cancelled."))
          console.log("")
          cleanupDiffListener()
          return response
        }

        spinner.start(colors.muted("thinking..."))
        try {
          response = await makeServerCall({
            type: "tool_result",
            runId: response.runId,
            tool: "_user_response",
            result: { answer: userAnswer, success: true }
          }, (label) => { spinner.text = colors.muted(suppressGenericPhaseLabel(label)) })
        } catch (userErr) {
          if ((userErr as ServerError).code === "USAGE_LIMIT") {
            budget.usage_limit.used++
            const waitMs = Math.min(10_000 * budget.usage_limit.used, budget.usage_limit.maxBackoffMs)
            spinner.stop()
            console.log(colors.warning(`  ⚠ Usage limit — waiting ${Math.round(waitMs / 1000)}s...`))
            await sleep(waitMs)
            spinner.start(colors.muted("retrying..."))
          }
          response = await callServer({
            type: "tool_result",
            runId: response.runId,
            tool: "_user_response",
            result: { answer: userAnswer, success: true }
          })
        }
        break
      }

      case "rate_limit_retry":
      case "usage_limit_retry":
      case "failure_retry": {
        const errorMsg = (response.error as string) || "Agent failed"
        const isRateLimit = transition.reason === "rate_limit_retry"
        const isUsageLimit = transition.reason === "usage_limit_retry"

        if (isRateLimit) {
          if (budget.rate_limit.used >= budget.rate_limit.max || !response.runId) {
            spinner.fail(colors.error(errorMsg))
            console.log(colors.muted(`  Exhausted rate-limit retries (${budget.rate_limit.used}/${budget.rate_limit.max})`))
            cleanupDiffListener()
            throw new Error(errorMsg)
          }
          budget.rate_limit.used++
          spinner.stop()
          console.log(colors.warning(`  ⚠ Rate limited — waiting ${Math.round(budget.rate_limit.backoffMs / 1000)}s (retry ${budget.rate_limit.used}/${budget.rate_limit.max})`))
          await sleep(budget.rate_limit.backoffMs)
          budget.rate_limit.backoffMs = Math.min(budget.rate_limit.backoffMs * 2, budget.rate_limit.maxBackoffMs)
          spinner.start(colors.muted("retrying after rate limit..."))
        } else if (isUsageLimit) {
          if (budget.usage_limit.used >= budget.usage_limit.max) {
            spinner.fail(colors.error(errorMsg))
            cleanupDiffListener()
            throw new Error(errorMsg)
          }
          budget.usage_limit.used++
          const waitMs = Math.min(budget.usage_limit.baseMs * Math.pow(2, budget.usage_limit.used - 1), budget.usage_limit.maxBackoffMs)
          spinner.stop()
          console.log(colors.warning(`  ⚠ Usage limit — waiting ${Math.round(waitMs / 1000)}s (retry ${budget.usage_limit.used}/${budget.usage_limit.max})`))
          await sleep(waitMs)
          spinner.start(colors.muted("retrying after usage limit..."))
        } else {
          if (stepCount === 0 || budget.failure.used >= budget.failure.max || !response.runId) {
            spinner.fail(colors.error(errorMsg))
            if (budget.rate_limit.used > 0 || budget.failure.used > 0) {
              console.log(colors.muted(`  Exhausted retries: ${budget.rate_limit.used} rate limit, ${budget.failure.used} failure retries`))
            }
            cleanupDiffListener()
            throw new Error(errorMsg)
          }
          budget.failure.used++
          budget.failure.consecutiveErrors++
          spinner.stop()
          if (budget.failure.consecutiveErrors >= budget.failure.maxConsecutive && budget.failure.used >= budget.failure.max) {
            console.log(colors.error(`  ${BOX.cross} ${errorMsg}`))
            console.log(colors.error(`  Task failed after ${budget.failure.used} retries and ${budget.failure.consecutiveErrors} consecutive errors.`))
            console.log("")
            cleanupDiffListener()
            throw new Error(errorMsg)
          }
          console.log(colors.error(`  ${BOX.cross} ${errorMsg}`))
          console.log(colors.muted(`    Auto-retrying (${budget.failure.used}/${budget.failure.max})...`))
          spinner.start(colors.muted("retrying..."))
        }

        // Re-issue _recovery to push the agent forward.
        const recoveryHint = isRateLimit
          ? "Rate limit was hit. The system waited and is retrying. Continue with the task using fewer tokens if possible."
          : isUsageLimit
            ? "Usage limit was hit. Reduce token usage and continue the task."
            : "Please fix the issue and continue. Do NOT give up. Respond with needs_tool to take the next action."

        try {
          response = await makeServerCall({
            type: "tool_result",
            runId: response.runId,
            tool: "_recovery",
            result: { error: errorMsg, success: false, hint: recoveryHint }
          }, (label) => { spinner.text = colors.muted(suppressGenericPhaseLabel(label)) })
        } catch (retryErr) {
          if ((retryErr as ServerError).code === "USAGE_LIMIT") {
            response = { ...response, status: "failed", error: errorMsg, errorCode: "usage_limit" }
          } else {
            response = await callServer({
              type: "tool_result",
              runId: response.runId,
              tool: "_recovery",
              result: { error: errorMsg, success: false, hint: recoveryHint }
            })
          }
        }
        break
      }

      case "completion_rejected": {
        // Triggered manually by client-side completion verification (handled in handleCompletion path).
        break
      }

      case "next_turn":
      default:
        break
    }
  }
}

// ─── Render the final completion state ───

async function renderCompletion(
  response: Record<string, unknown>,
  hasReasoning: boolean,
  lastDisplayedReasoning: string | null,
  taskSteps: Array<{ id: string; label: string; status?: string }>,
  completedSteps: Set<string>,
  stepCount: number,
): Promise<void> {
  let message = (response.message || response.content) as string | null
  const reasoning = response.reasoning as string | null

  if (message && message.trimStart().startsWith("{")) {
    try {
      const parsed = JSON.parse(message)
      if (parsed.content && typeof parsed.content === "string") {
        message = parsed.content
      }
    } catch { /* not JSON */ }
  }

  if (hasReasoning && reasoning && reasoning !== lastDisplayedReasoning && reasoning !== message) {
    await revealReasoning(reasoning)
  }

  console.log("")

  const summary = response.summary as Record<string, unknown> | null
  if (summary && summary.memoryUpdated && shouldRenderInlineForLegacy()) {
    // Phase 14 Stage 1: legacy MEMORY box. Stage 2+ will surface the
    // memory-update event as a structured Ink card so the alive UI shows
    // it without ASCII chrome. Until then the redirected console.log
    // would print these `│ Pattern: X │` lines as inline log entries
    // which read as visual noise — gate behind the helper.
    console.log("  " + boxTop("MEMORY", 36))
    if (summary.patternSaved) {
      console.log("  " + boxMid(colors.bright(`Pattern: ${summary.patternSaved}`)))
    }
    console.log("  " + boxMid(colors.muted("Shared with the whole team.")))
    console.log("  " + boxBot(36))
    console.log("")
  }

  if (taskSteps.length > 0) {
    for (const s of taskSteps) {
      completedSteps.add(s.id)
      s.status = "completed"
    }
    // Phase 14 Stage 1: in Ink mode the pipeline plan was already rendered
    // as a list of ToolCards at the start of the run (one per planned step,
    // upgraded from running → success as each lands). Re-rendering it as a
    // static box at completion is duplication. Stage 2 will replace
    // renderPipelineBox with a proper Ink ActionCard list summary.
    if (shouldRenderInlineForLegacy()) {
      const completedTask = response.task as Record<string, unknown> | null
      const title = (completedTask?.title as string) || `${completedSteps.size}/${taskSteps.length} COMPLETE`
      const goal = (completedTask?.goal as string) || ""
      renderPipelineBox(title, goal, taskSteps, completedSteps)
      console.log("")
    }
  }

  if (message) {
    // Phase 14 Stage 1: in Ink mode, the SUMMARY is rendered exclusively
    // via the Typewriter that consumes `assistant_message`. The legacy
    // boxTop/boxMid/boxBot console.log block would print the same text
    // instantly (via the Phase 13 console redirect) and the user would
    // read it twice — once as a static log entry, once as the slow
    // Typewriter reveal. Gate the box behind shouldRenderInlineForLegacy()
    // so legacy mode keeps its box and Ink mode gets the single source.
    if (shouldRenderInlineForLegacy()) {
      const rendered = renderMarkdown(message)
      const renderedLines = rendered.split("\n")
      console.log("  " + boxTop("SUMMARY", 50))
      for (const line of renderedLines) {
        console.log("  " + boxMid(line, 50))
      }
      console.log("  " + boxBot(50))
      console.log("")
    }
    // Phase 12 Stage 6: surface the completion message to the Ink stream
    // so AgentStream can render it via <Typewriter>. Use the unrendered
    // markdown text — the typewriter reveals plain characters and the
    // user reads it as the agent "writing", whereas a pre-rendered box
    // would land instantly and break the writing-feel.
    if (isInkActive() && message.trim().length > 0) {
      emitAgent({ type: "assistant_message", text: message })
    }
  }

  // Phase 16-fixup: the done-line emit is a legacy console renderer flourish.
  // In Ink mode, the assistant_message Typewriter (above) IS the completion
  // signal — re-emitting "✓ done" via raw stdout.write breaks Ink's reserved
  // region and causes the scroll glitch the user reports as Bug 4.
  if (shouldRenderInlineForLegacy()) {
    const doneText = `  ${colors.success(BOX.check)} done`
    const stepText = colors.muted(` ${BOX.dash} ${stepCount} steps`)
    process.stdout.write(doneText)
    await sleep(60)
    console.log(stepText)
    console.log("")
  }
}

// ─── Handle a needs_tool transition (single or batch) ───

interface NeedsToolCtx {
  hasReasoning: boolean
  lastDisplayedAction: string | null
  lastDisplayedReasoning: string | null
  currentRunId: string
  taskShown: boolean
  taskSteps: Array<{ id: string; label: string; status?: string }>
  completedSteps: Set<string>
  lastPipelineStepId: string | null
  /** Tool name from the previous turn — lets us coalesce consecutive reads. */
  prevTool: string | null
  /** Phase 10: chunk number (1-indexed) for the chunk-progress badge. */
  chunkIndex: number
  /** Phase 10: scratch — handler increments per Flash brief observed; the
   *  caller's helper threads it back into the result. */
  flashCallsThisTurn: number
  /** Phase 11 Stage 5: last awareness state we surfaced. Used to dedup the
   *  one-line transition log when the badge flips state turn-over-turn. */
  lastAwarenessState: "on_track" | "off_course" | "blocked" | null
  /** Phase 19: classified intent for the run. The task-rendering block
   *  inside handleNeedsTool reads this to decide whether the step
   *  transition log + initial pipeline box render (only when
   *  `runIntent === "implement"` AND the selective flag is on). */
  runIntent: "simple" | "summary" | "bug" | "implement" | null
  /** Phase 19: resolved value of the `taskDisplaySelective` sysbase
   *  setting. Captured once per run; toggling mid-run isn't supported. */
  taskDisplaySelective: boolean
  budget: RetryBudget
  /** Stage 1 of accountability-and-parallel-execution-sequencing plan:
   *  project-init classified repoState (constant for the run). Passed
   *  to `executeToolsBatch` so the parallel-batch cap relaxes from 3
   *  to 5 on `existing-large` repos where wide edits are more likely
   *  legitimate. Null when the project-init reasoner didn't fire. */
  projectInitRepoState: "empty" | "small" | "existing-small" | "existing-large" | null
}

interface NeedsToolResult {
  response: Record<string, unknown>
  stepCount?: number
  taskShown: boolean
  taskSteps: Array<{ id: string; label: string; status?: string }>
  lastDisplayedAction: string | null
  lastDisplayedReasoning: string | null
  lastPipelineStepId: string | null
  /** What tool ran this turn — caller threads it back into ctx.prevTool. */
  toolThisTurn: string | null
  /** Phase 10: chunk index after this turn (caller threads back into ctx.chunkIndex). */
  chunkIndex: number
  /** Phase 10: Flash calls observed this turn (chunk plan + chunk reflect briefs). */
  flashCallsThisTurn: number
  /** Phase 11 Stage 5: last awareness state we surfaced (for transition log dedupe). */
  lastAwarenessState: "on_track" | "off_course" | "blocked" | null
  /** Stage 5 of command-first-investigation: safe-read-only run_command
   *  calls observed at dispatch this turn. Caller accumulates into the
   *  per-run total recorded in RunSummary. */
  investigationCommandsThisTurn: number
  /** Stage 5 of agent-runtime-fixes plan: 0-hit web_search results
   *  observed this turn (0 or 1 — only one tool result per handleNeedsTool
   *  invocation). Caller accumulates into RunSummary.webSearchEmptyCount. */
  webSearchEmptyThisTurn: number
  /** Stage 4 of reasoning-chain-provider-parity plan: which path
   *  produced this turn's reasoning chain (server-side classification).
   *  Caller increments the structured-vs-synthesised counters in
   *  RunSummary based on observation. */
  perTurnReasoningSourceThisTurn: "structured" | "synthesised" | null
}

async function handleNeedsTool(
  response: Record<string, unknown>,
  spinner: ReturnType<typeof ora>,
  ctx: NeedsToolCtx,
  makeServerCall: (payload: Record<string, unknown>, phaseHandler?: (label: string) => void) => Promise<Record<string, unknown>>,
): Promise<NeedsToolResult> {
  const { hasReasoning, currentRunId, completedSteps, runIntent, taskDisplaySelective, budget } = ctx
  let { lastDisplayedAction, lastDisplayedReasoning, taskShown, taskSteps, lastPipelineStepId } = ctx
  // Stage 5 of command-first-investigation: local tally returned via
  // NeedsToolResult so runAgent can accumulate the per-run total.
  let investigationCommandsThisTurn = 0
  // Stage 5 of agent-runtime-fixes plan: 0-hit web_search tally for
  // RunSummary.webSearchEmptyCount.
  let webSearchEmptyThisTurn = 0
  // Stage 4 of reasoning-chain-provider-parity plan: capture the
  // per-turn reasoning source classification surfaced by the server.
  // Defaults to null when the response didn't carry the field (legacy
  // server build or unrelated kind like waiting_for_user).
  const sourceObserved = (response as Record<string, unknown>).perTurnReasoningSource
  const perTurnReasoningSourceThisTurn: "structured" | "synthesised" | null =
    sourceObserved === "structured" || sourceObserved === "synthesised" ? sourceObserved : null

  // Step transition handling
  const stepTransition = response.stepTransition as { complete?: string; start?: string } | undefined
  if (stepTransition?.complete) completedSteps.add(stepTransition.complete)

  const toolCalls = response.tools as Array<{ id: string; tool: string; args: Record<string, unknown> }> | undefined
  const isParallel = toolCalls && toolCalls.length > 1

  // Phase 19: gate the task-display block. When the selective flag is
  // on (default) AND the run's intent is anything other than
  // `implement`, skip the step-transition log + initial pipeline-box
  // emission entirely. The agent still has internal task structure
  // (chunked loop, reasoning briefs, memory) — it's just not surfaced
  // as a multi-step plan ceiling the conversation. See plan
  // `applied/2026-05-07-phase-19-task-display-selectivity.md`.
  const taskDisplayGated = taskDisplaySelective && runIntent !== null && runIntent !== "implement"

  // Pipeline display
  const task = response.task as Record<string, unknown> | null
  if (task && !taskDisplayGated) {
    const incomingSteps = (task.steps || []) as Array<{ id: string; label: string; status?: string }>
    for (const s of incomingSteps) {
      if (s.status === "completed" && s.id) completedSteps.add(s.id)
      const existing = taskSteps.find((ts) => ts.id === s.id)
      if (existing) existing.status = s.status
    }
    taskSteps = incomingSteps

    if (!taskShown) {
      spinner.stop()
      taskShown = true
      console.log("")
      // Phase 14 Stage 1: the big pipeline-plan box at the start of a run.
      // Stage 2 will replace this with a list of <ActionCard>s — one per
      // planned step, leading bullet greyed (○) until the step starts and
      // upgraded to ● in flight, ✔ on completion. Until then, gate the
      // legacy box behind shouldRenderInlineForLegacy() so Ink mode
      // doesn't show a `╭── ──╮` block as redirected log entries.
      if (shouldRenderInlineForLegacy()) {
        renderPipelineBox(task.title as string, task.goal as string, taskSteps, completedSteps)
        console.log("")
      }
      const activeStep = taskSteps.find((s) => s.status === "in_progress")
      lastPipelineStepId = activeStep?.id || null
      spinner.start(colors.muted("thinking..."))
    } else if (stepTransition) {
      spinner.stop()
      const completedStep = stepTransition.complete ? taskSteps.find((s) => s.id === stepTransition.complete) : undefined
      const startedStep = stepTransition.start ? taskSteps.find((s) => s.id === stepTransition.start) : undefined
      if (startedStep && startedStep.label && startedStep.id !== lastPipelineStepId) {
        console.log("")
        printStepTransition(completedStep?.label || null, startedStep.label)
        lastPipelineStepId = startedStep.id
      }
      spinner.start(colors.muted("thinking..."))
    }
  }

  if (isParallel) {
    spinner.stop()

    if (hasReasoning && response.reasoning && response.reasoning !== lastDisplayedReasoning) {
      lastDisplayedReasoning = response.reasoning as string
      await revealReasoning(response.reasoning as string)
    }

    const hasCommands = toolCalls!.some((tc) => tc.tool === "run_command")
    // Stage 5 of command-first-investigation: tally safe-read-only
    // investigation commands in the batch.
    for (const tc of toolCalls!) {
      if (tc.tool === "run_command" && isSafeReadOnlyCommand((tc.args as Record<string, unknown> | undefined)?.command)) {
        investigationCommandsThisTurn += 1
      }
    }

    console.log("")
    // Plan 2026-05-18-batch-heading-and-permission-label-polish.md issue #5:
    // partition-aware heading reads `parallel (N)` / `serial (N)` /
    // `mixed (P parallel + S serial)` so the user can predict the
    // dispatch pattern. Pre-Plan-2 a mixed batch (e.g. read + run_command)
    // collapsed to "batch", hiding that the run_command would be serialised.
    const heading = formatBatchHeading(toolCalls!)
    console.log(colors.accent(`    ${BOX.tl}${BOX.h}${BOX.h} ${heading.verb} `) + colors.muted(heading.detail))

    for (let i = 0; i < toolCalls!.length; i++) {
      const tc = toolCalls![i]
      const label = formatToolLabel(tc.tool, tc.args)
      await sleep(30)
      console.log(colors.accent(`    ${BOX.v}`) + `  ${colors.muted(BOX.ring)} ` + (label || `${tc.tool} ${JSON.stringify(tc.args)}`))
    }

    if (hasCommands) {
      console.log("")
      try {
        // Phase 12 Stage 4: surface a card per tool in the batch.
        response = await surfaceToolBatch(toolCalls!, () => executeToolsBatch(toolCalls!, response.runId as string, undefined, ctx.projectInitRepoState))
      } catch (batchError) {
        budget.failure.consecutiveErrors++
        console.log(colors.accent(`    ${BOX.bl}${BOX.h}${BOX.h}`) + ` ${colors.error("error:")} ` + colors.muted((batchError as Error).message))
        if (budget.failure.consecutiveErrors >= budget.failure.maxConsecutive) {
          console.log(colors.error(`\n  aborted: ${budget.failure.maxConsecutive} consecutive errors`))
          throw new Error("Too many consecutive tool errors")
        }
        spinner.start(colors.muted("thinking..."))
        response = await callServer({
          type: "tool_result",
          runId: response.runId,
          tool: "_recovery",
          result: { error: (batchError as Error).message, success: false }
        })
        return { response, taskShown, taskSteps, lastDisplayedAction, lastDisplayedReasoning, lastPipelineStepId, toolThisTurn: (response.tool as string) || null, chunkIndex: ctx.chunkIndex, flashCallsThisTurn: ctx.flashCallsThisTurn, lastAwarenessState: ctx.lastAwarenessState, investigationCommandsThisTurn, webSearchEmptyThisTurn, perTurnReasoningSourceThisTurn }
      }
      console.log(colors.accent(`    ${BOX.bl}${BOX.h}${BOX.h}`) + ` ${colors.success("done")}`)
      console.log("")
      spinner.start(colors.muted("thinking..."))
      return { response, taskShown, taskSteps, lastDisplayedAction, lastDisplayedReasoning, lastPipelineStepId, toolThisTurn: (response.tool as string) || null, chunkIndex: ctx.chunkIndex, flashCallsThisTurn: ctx.flashCallsThisTurn, lastAwarenessState: ctx.lastAwarenessState, investigationCommandsThisTurn, webSearchEmptyThisTurn, perTurnReasoningSourceThisTurn }
    }

    spinner.start(colors.muted(`  executing ${toolCalls!.length} tools...`))

    try {
      // Phase 12 Stage 4: surface a card per tool in the batch.
      response = await surfaceToolBatch(toolCalls!, () =>
        executeToolsBatch(toolCalls!, response.runId as string, (label) => {
          spinner.text = colors.muted(`  ${label}`)
        }, ctx.projectInitRepoState),
      )
      spinner.stop()

      // Phase 14 Stage 1: in Ink mode the running ToolCard set already
      // represents the in-flight tools; the overdraw below (cursor-up
      // + line-erase to upgrade ○ placeholders into ✔ checks in place)
      // both duplicates that information AND corrupts Ink's layout
      // state — the raw `\x1b[nA` escapes move the terminal cursor
      // outside Ink's reconciler model, which is the root cause of the
      // scroll-jump glitch users see during a run. Skip the entire
      // block when shouldRenderInlineForLegacy() is false.
      if (shouldRenderInlineForLegacy()) {
        process.stdout.write(`\x1b[${toolCalls!.length}A`)
        for (let i = 0; i < toolCalls!.length; i++) {
          const tc = toolCalls![i]
          const label = formatToolLabel(tc.tool, tc.args)
          process.stdout.write("\r\x1b[K")
          console.log(colors.accent(`    ${BOX.v}`) + `  ${colors.success(BOX.check)} ` + (label || `${tc.tool}`))
          await sleep(50)
        }

        console.log(colors.accent(`    ${BOX.bl}${BOX.h}${BOX.h}`) + ` ${colors.success("done")}`)
        console.log("")
      }
      spinner.start(colors.muted("thinking..."))
    } catch (batchError) {
      budget.failure.consecutiveErrors++
      spinner.stop()
      console.log(colors.accent(`    ${BOX.bl}${BOX.h}${BOX.h}`) + ` ${colors.error("error:")} ` + colors.muted((batchError as Error).message))
      if (budget.failure.consecutiveErrors >= budget.failure.maxConsecutive) {
        console.log(colors.error(`\n  aborted: ${budget.failure.maxConsecutive} consecutive errors`))
        throw new Error("Too many consecutive tool errors")
      }
      spinner.start(colors.muted("thinking..."))
      response = await callServer({
        type: "tool_result",
        runId: response.runId,
        tool: "_recovery",
        result: { error: (batchError as Error).message, success: false }
      })
    }
    return { response, taskShown, taskSteps, lastDisplayedAction, lastDisplayedReasoning, lastPipelineStepId, toolThisTurn: (response.tool as string) || null, chunkIndex: ctx.chunkIndex, flashCallsThisTurn: ctx.flashCallsThisTurn, lastAwarenessState: ctx.lastAwarenessState, investigationCommandsThisTurn, webSearchEmptyThisTurn, perTurnReasoningSourceThisTurn }
  }

  // ── SINGLE TOOL PATH ──
  const singleFromArray = (!response.tool && Array.isArray(response.tools) && (response.tools as Array<Record<string, unknown>>).length === 1)
    ? (response.tools as Array<Record<string, unknown>>)[0]
    : null
  if (singleFromArray) {
    response.tool = singleFromArray.tool
    response.args = singleFromArray.args
  }

  const pendingTaskStep = (response.taskStep as string) || null
  const args = (response.args || {}) as Record<string, unknown>

  const actionKey = `${response.tool}:${JSON.stringify(args)}:${response.reasoning || ""}`
  const isDuplicate = actionKey === lastDisplayedAction
  lastDisplayedAction = actionKey

  await sleep(hasReasoning ? 200 : 100 + Math.floor(Math.random() * 150))

  // Coalesce consecutive read_file calls: when the agent reads files one at
  // a time across turns, the per-turn reasoning narration ("I have read X.
  // Now I need to read Y.") is pure noise — the user already sees the
  // ▸ read X line. Skip the narration AND the heavy content preview when
  // both this turn AND the previous turn were reads.
  const isConsecutiveRead = response.tool === "read_file" && ctx.prevTool === "read_file"

  if (isHiddenStep(response.tool as string)) {
    spinner.text = colors.muted("scanning directory...")
  } else if (isDuplicate) {
    spinner.stop()
    spinner.start(colors.muted("thinking..."))
  } else {
    if (hasReasoning && response.reasoning && response.reasoning !== lastDisplayedReasoning && !isConsecutiveRead) {
      lastDisplayedReasoning = response.reasoning as string
      spinner.stop()
      await revealReasoning(response.reasoning as string)
    } else {
      spinner.stop()
    }

    if (response.tool === "batch_read") {
      const paths = (args.paths || []) as string[]
      console.log(`    ${colors.tool("read")} ${colors.muted(`${paths.length} files`)}`)
      for (const p of paths) {
        console.log(colors.muted(`      ${BOX.dot} ${p}`))
      }
    } else if (response.tool === "run_command") {
      const cmd = (args?.command as string) || ""
      const isInteractiveCmd = cmd ? /^npx\s+(--yes\s+)?(create-|@nestjs\/cli|@angular\/cli|nuxi)|^npm\s+(create|init)|^yarn\s+create|^pnpm\s+create/.test(cmd.trim()) : false
      if (isInteractiveCmd) {
        console.log(`    ${colors.accent(BOX.arrow)} ${colors.tool("run")} ${colors.bright(cmd)}`)
        console.log(colors.muted("    (interactive — answer prompts below)"))
      } else {
        spinner.start(colors.muted("  ") + colors.bright(cmd))
      }
    } else {
      const label = formatToolLabel(response.tool as string, args)
      const hasDiff = response.tool === "write_file" || response.tool === "edit_file"
      if (hasDiff) {
        let added = 0, removed = 0
        if (args.search !== undefined && response.tool === "edit_file") {
          const searchLines = ((args.search as string) || "").split("\n").length
          const replaceLines = ((args.replace as string) || "").split("\n").filter(Boolean).length
          removed = searchLines
          added = replaceLines
        } else if (args.line_start !== undefined && response.tool === "edit_file") {
          const lineStart = args.line_start as number
          const lineEnd = (args.line_end as number) || lineStart
          removed = lineEnd - lineStart + 1
          added = ((args.content as string) || "").split("\n").length
        } else if (args.insert_at !== undefined && response.tool === "edit_file") {
          added = ((args.content as string) || "").split("\n").length
        } else {
          const newContent = (args.content || args.patch || "") as string
          let oldContent: string | null = null
          try { oldContent = (await readFileTool(args.path as string)).content } catch { /* new file */ }
          const lineDiff = computeLineDiff(oldContent, newContent)
          added = lineDiff.added
          removed = lineDiff.removed
        }
        const parts: string[] = []
        if (added > 0) parts.push(colors.success(`+${added}`))
        if (removed > 0) parts.push(colors.error(`-${removed}`))
        const diffTag = parts.length > 0 ? " " + parts.join(colors.muted(" ")) : ""
        const tabHint = (added > 0 || removed > 0) ? colors.muted("  [Tab → diff]") : ""
        console.log(`    ${colors.accent(BOX.arrow)} ${label}${diffTag}${tabHint}`)
        if (added > 0 || removed > 0) {
          enableDiffExpand(currentRunId || (response.runId as string) || "")
        }
      } else {
        console.log(`    ${colors.accent(BOX.arrow)} ${label}`)
      }
    }

    if (response.tool !== "run_command") {
      spinner.start(colors.muted("thinking..."))
    }
  }

  const currentTool = response.tool as string
  const currentCmd = args?.command as string | undefined

  // Stage 5 of command-first-investigation: tally safe-read-only
  // investigation commands in the single-tool path. Counts at dispatch
  // time so a permission-deny or failed command still registers — the
  // metric measures the model's INTENT to investigate, not the result.
  if (currentTool === "run_command" && isSafeReadOnlyCommand(currentCmd)) {
    investigationCommandsThisTurn += 1
  }

  try {
    // Phase 12 Stage 4: surface a <ToolCard> for this dispatch in Ink mode.
    // Legacy console mode skips the emission and falls through to the
    // existing console.log lines.
    const toolEventId = nextToolEventId()
    const cardLabel = formatToolLabel(currentTool, args ?? {}) ?? currentTool
    // Phase 14 Stage 2: pass args so ActionCard can derive Verb(target).
    response = await surfaceToolCall(toolEventId, currentTool, cardLabel, args ?? {}, () =>
      executeTool(response as never, (label) => {
        spinner.text = colors.muted(suppressGenericPhaseLabel(label))
      }),
    )

    // Stage 5 of agent-runtime-fixes plan: count 0-hit web_search
    // results so RunSummary captures how often the prompt-level gating
    // missed. Reads the same `_errorCategory` the executor stamped.
    // Local counter returned via NeedsToolResult — runAgent accumulates.
    {
      const tr = response.lastToolResult as Record<string, unknown> | undefined
      if (currentTool === "web_search" && tr && tr._errorCategory === "web_search_empty") {
        webSearchEmptyThisTurn = 1
      }
    }

    // ─── Tool-result preview: replace the silent spinner gap with a one-liner ───
    // Skip the preview on consecutive reads — the ▸ read X line is enough.
    if (!isHiddenStep(currentTool) && !isConsecutiveRead) {
      const toolResult = response.lastToolResult as Record<string, unknown> | undefined
      const preview = renderToolResultPreview({ tool: currentTool, result: toolResult })
      if (preview) {
        spinner.stop()
        console.log(preview)
        spinner.start(colors.muted("thinking..."))
      }
      // Phase 5: render decision brief inline if the reason tool just returned one.
      if (currentTool === "reason" && toolResult && (toolResult as Record<string, unknown>).brief) {
        spinner.stop()
        // Phase 14 Stage 4: gate the legacy ASCII box; surface as a Peek in Ink mode.
        if (shouldRenderInlineForLegacy()) {
          renderDecisionBrief((toolResult as Record<string, unknown>).brief)
        } else {
          const brief = (toolResult as Record<string, unknown>).brief as Record<string, unknown>
          const kind = typeof brief.pipeline === "string" ? brief.pipeline : "decision"
          emitAgent({ type: "reasoning_brief", kind, briefData: brief })
        }
        spinner.start(colors.muted("thinking..."))
      }
    }

    // Phase 5: server may have attached a brief (on-error / on-completion) on the response.
    let flashCallsThisTurn = 0
    if (response.reasoningBrief) {
      spinner.stop()
      // Phase 14 Stage 4: gate the legacy ASCII box; surface as a Peek in Ink mode.
      if (shouldRenderInlineForLegacy()) {
        renderReasoningBrief(response.reasoningBrief)
      } else {
        const brief = response.reasoningBrief as Record<string, unknown>
        const kind = typeof brief.pipeline === "string" ? brief.pipeline : "unknown"
        emitAgent({ type: "reasoning_brief", kind, briefData: brief })
      }
      flashCallsThisTurn += 1
      spinner.start(colors.muted("thinking..."))
    }

    // Phase 10: per-turn chunk progress. The server attaches both briefs
    // when the chunked loop is active — reflection is the verdict on the
    // chunk we just executed, plan is for the next chunk to come. Increment
    // ctx.chunkIndex when a new plan arrives so the badge stays monotonic.
    const chunkPlanBrief = (response as Record<string, unknown>).chunkPlanBrief
    const chunkReflectionBrief = (response as Record<string, unknown>).chunkReflectionBrief
    // Phase 11 Stage 5: pull the awareness snapshot off the response so the
    // chunk-progress can render the badge + so we can detect state flips.
    const awareness = (response as Record<string, unknown>).awarenessSnapshot as { state: "on_track" | "off_course" | "blocked"; confidence: number; lastSignal?: string | null } | undefined
    if (chunkPlanBrief || chunkReflectionBrief) {
      spinner.stop()
      if (chunkPlanBrief) {
        ctx.chunkIndex += 1
        flashCallsThisTurn += 1
      }
      if (chunkReflectionBrief) flashCallsThisTurn += 1
      renderChunkProgress({
        chunkIndex: ctx.chunkIndex,
        plan: (chunkPlanBrief ?? null) as never,
        reflection: (chunkReflectionBrief ?? null) as never,
        awareness: awareness ?? null,
      })
      spinner.start(colors.muted("thinking..."))
      // Phase 11 Stage 2: snapshot before each new chunk's tools execute.
      // See the matching call at the initial-turn chunk site for rationale.
      if (chunkPlanBrief && currentRunId) {
        try { await createChunkSnapshot(process.cwd(), currentRunId, ctx.chunkIndex) } catch { /* best-effort */ }
      }
      // Phase 12 Stage 5: surface chunk-plan + awareness to the Ink Header.
      // Plan 2026-05-18-chunk-pulse-missing-diagnostic.md Stage 2 — same
      // pure helper as the initial-turn site. Symmetric emit logic
      // ensures both observers can't drift; the integration test pins
      // both call paths through one helper.
      {
        const perTurnChunkEvent = chunkPlanEventFromResponse(
          response as Record<string, unknown>,
          ctx.chunkIndex,
          isInkActive(),
        )
        if (perTurnChunkEvent) emitAgent(perTurnChunkEvent)
      }
      // Phase 16-fixup (Bug 3): surface chunk_plan + chunk_reflect briefs
      // through ReasoningPeek so the user actually sees what the chained
      // Flash decided each step. Header's chunk_plan event drives the
      // pulse; this drives the peek's content.
      if (isInkActive() && chunkPlanBrief) {
        emitAgent({ type: "reasoning_brief", kind: "chunk_plan", briefData: { chunkPlanBrief } as Record<string, unknown> })
      }
      if (isInkActive() && chunkReflectionBrief) {
        emitAgent({ type: "reasoning_brief", kind: "chunk_reflect", briefData: { chunkReflectionBrief } as Record<string, unknown> })
      }
    }
    // Phase 12 Stage 5: emit awareness_update on every turn that carries
    // a fresh snapshot (independent of chunk-plan presence — a tool-only
    // turn can still drop confidence).
    if (isInkActive() && awareness) {
      emitAgent({
        type: "awareness_update",
        state: awareness.state,
        confidence: awareness.confidence,
        lastSignal: awareness.lastSignal ?? null,
      })
    }
    // Phase 11 Stage 5: one-line transition log when the badge flips state
    // outside of a chunk-progress render (e.g. a tool turn that didn't carry
    // a chunk plan). Stays silent on no-change and on the initial on_track
    // baseline.
    if (awareness && ctx.lastAwarenessState && awareness.state !== ctx.lastAwarenessState) {
      const transition = describeAwarenessTransition(ctx.lastAwarenessState, awareness.state)
      if (transition) {
        spinner.stop()
        console.log("  " + transition)
        spinner.start(colors.muted("thinking..."))
      }
    }
    if (awareness) ctx.lastAwarenessState = awareness.state
    // Stash on ctx so it threads to the result via the helper below.
    ctx.flashCallsThisTurn = flashCallsThisTurn

    if (currentTool === "run_command") {
      spinner.stop()
      const toolResult = response.lastToolResult as Record<string, unknown> | undefined
      if (toolResult?.skipped) {
        console.log(colors.warning(`  ⚠ `) + colors.muted(currentCmd) + colors.warning(" (run manually)"))
      } else if (toolResult?.timedOut) {
        console.log(colors.warning(`  ⏱ `) + colors.muted(currentCmd) + colors.warning(" (timed out)"))
        console.log(colors.warning("  command timed out — continuing task..."))
      } else if (toolResult?.interactive) {
        console.log("")
        console.log(`  ${colors.success(BOX.check)} ` + colors.muted(currentCmd) + colors.success(" (done)"))
        console.log(colors.accent("  continuing task..."))
      } else {
        console.log(`  ${colors.success(BOX.check)} ` + colors.muted(currentCmd))
      }
      spinner.start(colors.muted("thinking..."))
    }

    if (pendingTaskStep && taskSteps.length > 0) {
      const step = taskSteps.find((s) => s.id === pendingTaskStep)
      if (step) completedSteps.add(step.id)
    }
  } catch (toolError) {
    budget.failure.consecutiveErrors++
    spinner.stop()
    if (currentTool === "run_command") {
      console.log(colors.error(`  ${BOX.cross} `) + colors.muted(currentCmd) + colors.error(` — ${(toolError as Error).message}`))
    } else {
      console.log(colors.error(`    ${BOX.cross} ${(toolError as Error).message}`))
    }

    if (budget.failure.consecutiveErrors >= budget.failure.maxConsecutive) {
      console.log(colors.error(`\n  aborted: ${budget.failure.maxConsecutive} consecutive errors`))
      console.log("")
      throw new Error("Too many consecutive tool errors")
    }

    spinner.start(colors.muted("thinking..."))
    response = await callServer({
      type: "tool_result",
      runId: response.runId,
      tool: response.tool,
      result: {
        error: (toolError as Error).message,
        success: false,
        path: args?.path || undefined
      }
    })
  }

  return { response, taskShown, taskSteps, lastDisplayedAction, lastDisplayedReasoning, lastPipelineStepId, toolThisTurn: (response.tool as string) || null, chunkIndex: ctx.chunkIndex, flashCallsThisTurn: ctx.flashCallsThisTurn, lastAwarenessState: ctx.lastAwarenessState, investigationCommandsThisTurn, webSearchEmptyThisTurn, perTurnReasoningSourceThisTurn }
}
